[package]
org = "ballerina"
name = "data.xmldata"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["xml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data-xmldata"
license = ["Apache-2.0"]
distribution = "2201.8.6"
export = ["data.xmldata"]

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data-native"
version = "@toml.version@"
path = "../native/build/libs/data.xmldata-native-@project.version@.jar"
