[package]
org = "ballerina"
name = "data"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["xml"]
repository = "https://github.com/hasithaa/module-ballerina-data"
license = ["Apache-2.0"]
distribution = "2201.8.1"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "data-native"
version = "0.1.0"
path = "../native/build/libs/data-native-0.1.0-SNAPSHOT.jar"
