[package]
org = "ballerina"
name = "data.xml"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["xml"]
repository = "https://github.com/ballerina-platform/module-ballerina-data.xml"
license = ["Apache-2.0"]
distribution = "2201.8.1"
export = ["data.xml"]

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "data-native"
version = "0.1.0"
path = "../native/build/libs/data-xml-native-0.1.0-SNAPSHOT.jar"
